=== daclink/cloudSuite/cloudSuite/html/schema/collection.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema 
version="0.2"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

<xsd:annotation>
  <xsd:appinfo>CloudSuite set schema</xsd:appinfo>
  <xsd:documentation xml:lang="en">
    
    This is the object defenition for the set type object
    used in CloudSuite.info
    Copyright 2011 Drew A. Clinkenbeard.
    All rights reserved.
  </xsd:documentation>
</xsd:annotation>
<!-- define simple elements -->
<xsd:element name="product" type="xsd:string"/>
<xsd:element name="version" type="xsd:string"/>
<xsd:element name="kind" type="xsd:string"/>
<xsd:element name="path" type="xsd:string"/>
<xsd:element name="flag" type="xsd:string"/>
<xsd:element name="type" type="xsd:string"/>
<xsd:element name="desc" type="xsd:string"/>
<xsd:element name="ownerID" type="xsd:string"/>
<xsd:element name="clearance" type="xsd:string"/>
<xsd:element name="created" type="xsd:string"/>
<xsd:element name="methodName" />
<xsd:element name="parameterString" type="xsd:string"/>
<xsd:element name="sequenceNumber" type="xsd:string"/>
<xsd:element name="input" type="xsd:string"/>
<xsd:element name="output" type="xsd:string"/>


<!-- define attributes-->
<xsd:attribute name="name" type="xsd:string" />
<xsd:attribute name="id" type="xsd:string" />

<!-- define complex elements -->
			
<xsd:element name="module">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element ref="methodName" />
			<xsd:element ref="parameterString"/>
                        <xsd:element ref="sequenceNumber" />
                        <xsd:element ref="desc" />
                        <xsd:element ref="input" />
                        <xsd:element ref="output" />
		</xsd:sequence>
		<xsd:attribute ref="name" use="required"/>
		<xsd:attribute ref="id" use="required"/>
	</xsd:complexType>		
</xsd:element>


<xsd:element name="collection">
	<xsd:complexType>
		<xsd:sequence>
                    <xsd:element ref="desc" /> 
                    <xsd:element ref="ownerID" />
                    <xsd:element ref="clearance" />
                    <xsd:element ref="created" />
                    <xsd:element ref="module" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute ref="name" use="required"/>
		<xsd:attribute ref="id" use="required"/>
	</xsd:complexType>		
</xsd:element>
</xsd:schema>

=== daclink/cloudSuite/cloudSuite/html/collections/30.biological.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : collection.xml
    Created on : February 24, 2012, 7:21 AM
    Author     : drew
    Description:
-->

<collection name="biological" id="1"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="http://www.cloudsuite.info/schema/collection.xsd"
            >
    <desc>
        A Collection of modules used in genetically inspired computing.
    </desc>
    <ownerID>22</ownerID>
    <clearance>10</clearance>
    <created>2012.02.11</created>
    <module name="ga" id="7">
        <methodName></methodName>
        <parameterString></parameterString>
        <sequenceNumber></sequenceNumber>
        <desc>Genetic algorithm for pattern matching</desc>
        <input></input>
        <output></output>
    </module>
    <module name="neuro" id="8">
        <methodName></methodName>
        <parameterString></parameterString>
        <sequenceNumber></sequenceNumber>
        <desc>Initializing Neural net</desc>
        <input></input>
        <output></output>
    </module>
</collection>

=== daclink/cloudSuite/cloudSuite/html/collections/cryptography.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : collection.xml
    Created on : February 24, 2012, 7:21 AM
    Author     : drew
    Description:
-->

<collection name="cryptography" id="20"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="http://www.cloudsuite.info/schema/collection.xsd"
            >
    <ownerID>22</ownerID>
    <clearance>10</clearance>
    <created>2012.02.11</created>
    <module name="rsa" id="21">
        <methodName></methodName>
        <parameterString></parameterString>
        <sequenceNumber></sequenceNumber>
        <desc>Encrypt using RSA</desc>
        <input></input>
        <output></output>
    </module>
    <module name="hash-crack" id="232">
        <methodName></methodName>
        <parameterString></parameterString>
        <sequenceNumber></sequenceNumber>
         <desc>Crack a hash file.</desc>
        <input></input>
        <output></output>
    </module>
    <desc>A Collection of modules used for cryptographic purposes.</desc>
</collection>

=== daclink/cloudSuite/cloudSuite/html/collections/10.graphing.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : collection.xml
    Created on : February 24, 2012, 7:21 AM
    Author     : drew
    Description:
-->

<collection name="Graphing" id="10"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="http://www.cloudsuite.info/schema/collection.xsd"
            >
    <desc>
        A Collection of modules used to display quantative data.
    </desc>
    <ownerID>22</ownerID>
    <clearance>10</clearance>
    <created>2012.02.11</created>
    <module name="graphs" id="11">
        <methodName></methodName>
        <parameterString></parameterString>
        <sequenceNumber></sequenceNumber>
        <desc>Chart some data yo</desc>
        <input></input>
        <output></output>
    </module>
</collection>
