=== daclink/cloudSuite/cloudSuite/html/schema/group.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    
    
    <!-- 
targetNamespace="http://cloudsuite.info"
xmlns:cs="http://cloudsuite.info"-->

    <xsd:annotation>
      <xsd:appinfo>CloudSuite Group schema</xsd:appinfo>
      <xsd:documentation xml:lang="en">
        This is the object defenition for the group type object
        used in CloudSuite.info
        Copyright 2012 Drew A. Clinkenbeard.
        All rights reserved.
      </xsd:documentation>
    </xsd:annotation>

    <!-- define simple elements -->
    <!-- xsd:element name="group" type="xsd:s   tring"/-->
    <!-- xsd:element name="member" type="xsd:string"/-->
    <!-- xsd:element name="id" type="xsd:string"/-->
     
    <!-- define attributes-->
    <xsd:attribute name="name" type="xsd:string" />
    <xsd:attribute name="id" type="xsd:string" />
   
   <!-- define complex types -->
 
 <xsd:element name="user">
        <xsd:complexType>
            <xsd:attribute ref="id" use="required"/>
        </xsd:complexType>
 </xsd:element>
 <xsd:element name="lab">
        <xsd:complexType>
            <xsd:attribute ref="id" use="required"/>
        </xsd:complexType>
 </xsd:element>
 <xsd:element name="collection">
        <xsd:complexType>
            <xsd:attribute ref="id" use="required"/>
        </xsd:complexType>
 </xsd:element>
 <xsd:element name="module">
        <xsd:complexType>
            <xsd:attribute ref="id" use="required"/>
        </xsd:complexType>
 </xsd:element>
 
 <xsd:element name="group">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="user" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element ref="lab" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element ref="collection" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element ref="module" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute ref="id" use="required"/>
            <xsd:attribute ref="name" use="required"/>
        </xsd:complexType>
    </xsd:element>
 
    <xsd:element name="groups">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="group" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
</xsd:schema>

=== daclink/cloudSuite/cloudSuite/html/schema/group.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : group.xml
    Created on : September 30, 2012, 9:25 AM
    Author     : drew
    Description:
        Purpose of the document follows.
-->

<groups  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='null'
   xsi:schemaLocation='null group.xsd'>
    <group id="20" name="comp501">
        <user id="1"></user>
        <user id="2"></user>
        <user id="3"></user>
        <lab id="4"></lab>
        <lab id="5"></lab>
        <lab id="6"></lab>
        <collection id="7"></collection>
        <collection id="8"></collection>
        <collection id="9"></collection>
        <module id="12"></module>
        <module id="13"></module>
        <module id="11"></module>
    </group>
    <group id="21" name="comp502">
        <user id="1"></user>
        <user id="14"></user>
        <user id="15"></user>
        <lab id="4"></lab>
        <lab id="5"></lab>
        <lab id="16"></lab>
        <collection id="17"></collection>
        <collection id="18"></collection>
        <collection id="9"></collection>
        <module id="19"></module>
        <module id="12"></module>
        <module id="111"></module>
    </group>

</groups>
