=== daclink/cloudSuite/cloudSuite/html/schema/lab.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:annotation>
      <xsd:appinfo>CloudSuite lab schema</xsd:appinfo>
      <xsd:documentation xml:lang="en">
        This is the object defenition for the lab object type
        used in CloudSuite.info
        Copyright 2012 Drew A. Clinkenbeard.
        All rights reserved.
      </xsd:documentation>
    </xsd:annotation>
    
     <!-- define simple elements -->
    <xsd:element name="owner" type="xsd:string"/>
    <xsd:element name="group" type="xsd:string"/>
    <xsd:element name="everyone" type="xsd:string"/>
    <xsd:element name="flag" type="xsd:string"/>
    <xsd:element name="value" type="xsd:string"/>
    <xsd:element name="settings" type="xsd:string"/>
    <xsd:element name="method" type="xsd:string"/>
    <xsd:element name="attributeString" type="xsd:string"/>
    <xsd:element name="lastrunDate" type="xsd:string"/>
    <xsd:element name="lastRunUser" type="xsd:string"/>
    
     <!-- define attributes-->
    <xsd:attribute name="id" type="xsd:string" />
    <xsd:attribute name="seqNumber" type="xsd:string"/>
    
    <!-- define complex elements -->
   
    <xsd:element name="module">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="settings" maxOccurs="unbounded"/>
                <xsd:element ref="method" />
                <xsd:element ref="attributeString" /> 
            </xsd:sequence>
            <xsd:attribute ref="id" use="required"/>
            <xsd:attribute ref="seqNumber" use="required"/>
       </xsd:complexType>
       <!--xsd:unique name="UniqueSeqNumber">
           <xsd:selector xpath="//module"/>
           <xsd:field xpath="@seqNumber"/>
       </xsd:unique-->
    </xsd:element>
    
    <xsd:element name="permissions">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="owner" maxOccurs="1"/>
                <xsd:element ref="group" maxOccurs="1"/>
                <xsd:element ref="everyone" maxOccurs="1"/>
            </xsd:sequence>
       </xsd:complexType>
   </xsd:element>
        
    <xsd:element name="lab">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="owner" maxOccurs="1"/>
                <xsd:element ref="permissions" maxOccurs="1"/>
                <xsd:element ref="module" minOccurs="0" maxOccurs="1"/>
            </xsd:sequence>
            <xsd:attribute ref="id" use="required"/>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== daclink/cloudSuite/cloudSuite/html/schema/lab.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : lab.xml
    Created on : February 23, 2012, 6:54 PM
    Author     : drew
    Description:
        Purpose of the document follows.
-->

<ns0:lab  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='null'
   xsi:schemaLocation='null lab.xsd' ns0:id="">
    <owner></owner>
    <permissions>
        <owner></owner>
        <group></group>
        <everyone></everyone>
    </permissions>
    <module ns0:id="" ns0:seqNumber="">
        <settings>
            <flag></flag>
            <value></value>
        </settings>
        <settings>
            <flag></flag>
            <value></value>
        </settings>
        <settings>
            <flag></flag>
            <value></value>
        </settings>
    </module>
    <module ns0:id="" ns0:seqNumber="">
        <settings>
            <flag></flag>
            <value></value>
        </settings>
        <settings>
            <flag></flag>
            <value></value>
        </settings>
        <settings>
            <flag></flag>
            <value></value>
        </settings>
    </module>
    <module ns0:id="" ns0:seqNumber="">
        <settings>
            <flag></flag>
            <value></value>
        </settings>
        <settings>
            <flag></flag>
            <value></value>
        </settings>
        <settings>
            <flag></flag>
            <value></value>
        </settings>
    </module>

</ns0:lab>
